In [1]:
import torch

## 创建张量 tensor
    1.torch.arange
    2.x.size()
    3.x.reshape
    4.torch.ones /zeros  /rand


In [2]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
print(x.size())

torch.Size([12])


In [4]:
y = x.reshape(3,4)
print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
print(torch.zeros(3,4))
print(torch.ones(4,5))
print(torch.rand(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.7794, 0.1670, 0.9480, 0.2279],
        [0.1848, 0.1444, 0.7666, 0.2944],
        [0.7299, 0.4177, 0.1188, 0.1612]])


## 运算 

    + - * / ^

In [6]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))